
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://donzwloisqhhbicqriop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvbnp3bG9pc3FoaGJpY3FyaW9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0Mjk0ODQsImV4cCI6MjA2MDAwNTQ4NH0.R51Mpm78iTly9CDnzGBo9ZUuCAX1nr7evlDQy8bQsIQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
